server {
    listen 80;
    listen [::]:80;
    server_name _;
    
    # Permet a Certbot validar el domini
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirigeix automàticament tot el trànsit HTTP a HTTPS
    return 301 https://$host$request_uri;
}