server {
    listen 80;
    listen [::]:80;
    server_name _;
    
    # Permet a Certbot validar el domini
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirigeix automàticament tot el trànsit HTTP a HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name _;


# Rutes dels certificats de Let's Encrypt
    ssl_certificate /etc/letsencrypt/live/98bf8ebb-e29f-4d8f-aee0.d42a4cb7f33b.isard.nuvulet.itb.cat/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/98bf8ebb-e29f-4d8f-aee0.d42a4cb7f33b.isard.nuvulet.itb.cat/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        # 'php-app' ha de coincidir amb el nom del servei del teu contenidor de PHP al docker-compose
        proxy_pass http://php-app:80; 
        # proxy_pass http://172.30.1.48:3000; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
