server {
    listen 80;
    listen [::]:80;
    server_name 172.30.1.48.nip.io localhost;
    
    # Redirigeix automàticament tot el trànsit HTTP a HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name 172.30.1.48.nip.io localhost;

    # Ruta als certificats que hem creat amb mkcert
    ssl_certificate /etc/nginx/certs/cues.crt
    ssl_certificate_key /etc/nginx/certs/cues.key

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        # 'php-app' ha de coincidir amb el nom del servei del teu contenidor de PHP al docker-compose
        proxy_pass http://php-app:3000; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
